server:
  port: 20001
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    druid:
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      valid-connection-checker-class-name: com.alibaba.druid.pool.vendor.MSSQLValidConnectionChecker
      validation-query: SELECT 1 FROM DUAL
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.wmyskxz.blog.entity
